# Generated by Django 4.1 on 2022-08-08 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("headquarters_country", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Brand",
                "verbose_name_plural": "Brands",
            },
        ),
        migrations.CreateModel(
            name="Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("year_of_issue", models.CharField(max_length=4)),
                ("body_style", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Model",
                "verbose_name_plural": "Models",
            },
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField()),
                ("mileage", models.IntegerField()),
                ("exterior_color", models.CharField(max_length=255)),
                ("interior_color", models.CharField(max_length=255)),
                ("fuel_type", models.CharField(max_length=50)),
                ("transmission_type", models.CharField(max_length=50)),
                ("engine_volume", models.FloatField()),
                ("is_on_sale", models.BooleanField()),
                (
                    "brand_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="cars_app.brand"
                    ),
                ),
                (
                    "model_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="cars_app.model"
                    ),
                ),
            ],
            options={
                "verbose_name": "Car",
                "verbose_name_plural": "Cars",
            },
        ),
    ]
